apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cardioui
      type: ml-api
  template:
    metadata:
      labels:
        app: cardioui
        type: ml-api
    spec:
      containers:
        - name: ml-api
          image: "debangshubh/cardioui-ml-api:1.0"