apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: cardioui
    type: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002